[theme]

# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base = "light"

# Primary accent color for interactive elements.
primaryColor = "#CACAFF"

# Background color for the main content area.
backgroundColor = "#E6EDFE"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor ="#CACAFF"

# Color used for almost all text.
textColor = "#5b5cbd"

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
font = "sans serif"